# Generated by Django 5.2.3 on 2025-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=100)),
                ('carpeta_entrada', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('bid', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('uc', models.CharField(max_length=50)),
                ('cedidos', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
