# Generated by Django 5.2.3 on 2025-06-19 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('archivo_cad', models.FileField(upload_to='autocad/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=50)),
                ('card', models.CharField(max_length=50)),
                ('uc', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms.formularioglobal')),
            ],
        ),
    ]
