# Generated by Django 5.2.4 on 2025-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioglobal',
            name='activo',
            field=models.BooleanField(default=True, help_text='1=Activo, 0=Eliminado'),
        ),
    ]
