# Generated by Django 5.2.4 on 2025-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formularioglobal_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='departamento_asignado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='equipo_contratista',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='regional_asignada',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(blank=True, choices=[('', 'Sin rol asignado'), ('admin', 'Administrador'), ('contratista', 'Contratista'), ('ejecutor', 'Ejecutor/Interventor'), ('gestion', 'Gestión'), ('planeacion', 'Planeación')], default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='forms_customuser',
        ),
    ]
