# Generated by Django 5.2.3 on 2025-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formularioglobal_itemformulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioglobal',
            name='archivo_cad',
            field=models.FileField(blank=True, null=True, upload_to='autocad/'),
        ),
    ]
