# Generated by Django 5.2.3 on 2025-07-07 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formularioglobal_archivo_cad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraNueva',
            fields=[
                ('id', models.AutoField(db_column='AC_ID_PIR', primary_key=True, serialize=False)),
                ('cod_est', models.CharField(blank=True, db_column='AC_COD_EST_PIR', max_length=50, null=True)),
                ('apoyo', models.CharField(blank=True, db_column='AC_APOYO_PIR', max_length=50, null=True)),
                ('material', models.CharField(blank=True, db_column='AC_MATERIAL_PIR', max_length=50, null=True)),
                ('altura', models.DecimalField(blank=True, db_column='AC_ALTURA_PIR', decimal_places=2, max_digits=5, null=True)),
                ('tipo_red', models.CharField(blank=True, db_column='AC_TIPO_RED_PIR', max_length=50, null=True)),
                ('poblacion', models.CharField(blank=True, db_column='AC_POBLACION_PIR', max_length=50, null=True)),
                ('disposicion', models.CharField(blank=True, db_column='AC_DISPOSICION_PIR', max_length=50, null=True)),
                ('kgf', models.DecimalField(blank=True, db_column='AC_KGF_PIR', decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(db_column='AC_CREATED_AT_PIR', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='AC_UPDATED_AT_PIR')),
            ],
            options={
                'db_table': 'AC_ESTRUCTURA_NUEVA_PIR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstructuraRetirada',
            fields=[
                ('id', models.AutoField(db_column='AC_ID_PIR', primary_key=True, serialize=False)),
                ('cod_est', models.CharField(blank=True, db_column='AC_COD_EST_PIR', max_length=50, null=True)),
                ('apoyo', models.CharField(blank=True, db_column='AC_APOYO_PIR', max_length=50, null=True)),
                ('material', models.CharField(blank=True, db_column='AC_MATERIAL_PIR', max_length=50, null=True)),
                ('altura', models.DecimalField(blank=True, db_column='AC_ALTURA_PIR', decimal_places=2, max_digits=5, null=True)),
                ('tipo_red', models.CharField(blank=True, db_column='AC_TIPO_RED_PIR', max_length=50, null=True)),
                ('punto', models.CharField(blank=True, db_column='AC_PUNTO_PIR', max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_column='AC_CREATED_AT_PIR', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='AC_UPDATED_AT_PIR')),
            ],
            options={
                'db_table': 'AC_ESTRUCTURA_RETIRADA_PIR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProyectoInfo',
            fields=[
                ('id', models.AutoField(db_column='AC_ID_PIR', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='AC_NOMBRE_PIR', max_length=200)),
                ('ot_mano_obra', models.CharField(blank=True, db_column='AC_OT_MANO_OBRA_PIR', max_length=50, null=True)),
                ('ot_materia', models.CharField(blank=True, db_column='AC_OT_MATERIA_PIR', max_length=50, null=True)),
                ('contrato', models.CharField(blank=True, db_column='AC_CONTRATO_PIR', max_length=50, null=True)),
                ('pro_terc', models.CharField(blank=True, db_column='AC_PRO_TERC_PIR', max_length=50, null=True)),
                ('created_at', models.DateTimeField(db_column='AC_CREATED_AT_PIR', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='AC_UPDATED_AT_PIR')),
            ],
            options={
                'db_table': 'AC_PROYECTO_INFO_PIR',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='FormularioDESS',
        ),
        migrations.AlterModelOptions(
            name='formularioglobal',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='formularioglobal',
            name='archivo_cad',
        ),
        migrations.RemoveField(
            model_name='formularioglobal',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='formularioglobal',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='formularioglobal',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='alimentador',
            field=models.CharField(blank=True, db_column='AC_ALIMENTADOR_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='barrio_vereda',
            field=models.CharField(blank=True, db_column='AC_BARRIO_VEREDA_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='circuito',
            field=models.CharField(blank=True, db_column='AC_CIRCUITO_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='created_at',
            field=models.DateTimeField(db_column='AC_CREATED_AT_PIR', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='direccion',
            field=models.CharField(blank=True, db_column='AC_DIRECCION_PIR', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='municipio',
            field=models.CharField(blank=True, db_column='AC_MUNICIPIO_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='nivel_tension',
            field=models.CharField(blank=True, db_column='AC_NIVEL_TENSION_PIR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='numero_x',
            field=models.IntegerField(blank=True, db_column='AC_NUMERO_X_PIR', null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='numero_y',
            field=models.IntegerField(blank=True, db_column='AC_NUMERO_Y_PIR', null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='numero_z',
            field=models.IntegerField(blank=True, db_column='AC_NUMERO_Z_PIR', null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='regional',
            field=models.CharField(blank=True, db_column='AC_REGIONAL_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='trabajo',
            field=models.CharField(blank=True, db_column='AC_TRABAJO_PIR', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='AC_UPDATED_AT_PIR'),
        ),
        migrations.AlterField(
            model_name='formularioglobal',
            name='id',
            field=models.AutoField(db_column='AC_ID_PIR', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='formularioglobal',
            table='AC_FORMULARIO_GLOBAL_PIR',
        ),
        migrations.AddField(
            model_name='estructuranueva',
            name='formulario',
            field=models.ForeignKey(db_column='AC_FORMULARIO_ID_PIR', on_delete=django.db.models.deletion.CASCADE, to='forms.formularioglobal'),
        ),
        migrations.AddField(
            model_name='estructuraretirada',
            name='formulario',
            field=models.ForeignKey(db_column='AC_FORMULARIO_ID_PIR', on_delete=django.db.models.deletion.CASCADE, to='forms.formularioglobal'),
        ),
        migrations.AddField(
            model_name='proyectoinfo',
            name='formulario',
            field=models.OneToOneField(db_column='AC_FORMULARIO_ID_PIR', on_delete=django.db.models.deletion.CASCADE, to='forms.formularioglobal'),
        ),
        migrations.DeleteModel(
            name='ItemFormulario',
        ),
    ]
