# Generated by Django 5.2.4 on 2025-07-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_customuser_options_and_more'),
        ('forms', '0003_formularioiteracion'),
    ]

    operations = [
    ]
