# Generated by Django 5.2.3 on 2025-07-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_estructuranueva_estructuraretirada_proyectoinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estructuranueva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estructuraretirada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='formularioglobal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proyectoinfo',
            options={'managed': False},
        ),
    ]
