# Generated by Django 5.2.4 on 2025-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_sync_database_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='formularioiteracion',
            name='unique_iteracion_per_session',
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='equipo_contratista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='regional_asignada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='desmantelado',
            field=models.BooleanField(default=False, help_text='Desmantelado - Solo estructura retirada habilitada'),
        ),
        migrations.AddField(
            model_name='formularioglobal',
            name='montaje_integral',
            field=models.BooleanField(default=False, help_text='Montaje integral - Deshabilita campos UC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('contratista', 'Contratista'), ('ejecutor', 'Ejecutor/Interventor'), ('gestion', 'Gestión'), ('planeacion', 'Planeación')], default='contratista', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='formularioiteracion',
            unique_together={('session_key', 'seccion', 'numero_iteracion', 'estado')},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='FORMS_CUSTOMUSER',
        ),
    ]
