# Generated by Django 5.2.1 on 2025-08-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioglobal',
            name='desmantelado',
        ),
        migrations.RemoveField(
            model_name='formularioglobal',
            name='montaje_integral',
        ),
    ]
