#!/usr/bin/env python
import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dess.settings')
django.setup()

from django.db.migrations.recorder import MigrationRecorder
from django.db import connection

# Inicializar el recorder de migraciones
recorder = MigrationRecorder(connection)

try:
    # Marcar la migración 0002 como aplicada
    recorder.record_applied('forms', '0002_formularioglobal_activo')
    print("✅ Migración 0002 marcada como aplicada")
except Exception as e:
    print(f"ℹ️ Migración 0002: {e}")

try:
    # Crear la tabla manualmente
    cursor = connection.cursor()
    cursor.execute("""
    CREATE TABLE FORMULARIO_ITERACIONES (
        ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY, 
        SESSION_KEY NVARCHAR2(40) NULL, 
        FORMULARIO_ID NVARCHAR2(50) NULL, 
        SECCION NVARCHAR2(20) NULL, 
        ESTADO NVARCHAR2(10) NULL, 
        NUMERO_ITERACION NUMBER(11) NOT NULL, 
        NOMBRE_PROYECTO NVARCHAR2(200) NULL, 
        BANCO_PROYECTO NVARCHAR2(100) NULL, 
        CONTRATO NVARCHAR2(200) NULL, 
        MUNICIPIO NVARCHAR2(100) NULL, 
        DEPARTAMENTO NVARCHAR2(100) NULL, 
        REGIONAL NVARCHAR2(100) NULL, 
        LATITUD_INICIAL NUMBER(12, 8) NULL, 
        LONGITUD_INICIAL NUMBER(12, 8) NULL, 
        LATITUD_FINAL NUMBER(12, 8) NULL, 
        LONGITUD_FINAL NUMBER(12, 8) NULL, 
        DIRECCION NVARCHAR2(200) NULL, 
        CANTIDAD NUMBER(11) NOT NULL, 
        DATOS_ESPECIFICOS NCLOB NOT NULL, 
        FECHA_CREACION TIMESTAMP NOT NULL, 
        FECHA_ACTUALIZACION TIMESTAMP NOT NULL, 
        USUARIO_ID NUMBER(19) NULL
    )
    """)
    print("✅ Tabla FORMULARIO_ITERACIONES creada")
except Exception as e:
    if "name is already used" in str(e).lower() or "already exists" in str(e).lower():
        print("ℹ️ Tabla FORMULARIO_ITERACIONES ya existe")
    else:
        print(f"❌ Error creando tabla: {e}")

try:
    # Marcar la migración 0003 como aplicada
    recorder.record_applied('forms', '0003_crear_tabla_iteraciones')
    print("✅ Migración 0003 marcada como aplicada")
except Exception as e:
    print(f"ℹ️ Migración 0003: {e}")

print("\n🎉 Sistema de iteraciones listo para usar!")
