"""
Django settings for FormPIR project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# IMPORTANTE: Importar el parche de Oracle ANTES que cualquier otra cosa
import sys
import os
# Añadir directorio raíz del proyecto al path
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.insert(0, project_root)

try:
    import oracle_patch  # Parche para usar oracledb en lugar de cx_Oracle
except ImportError:
    pass

from pathlib import Path
import django
from django.utils.translation import gettext_lazy as _
import oracledb

# Configuración de idioma y zona horaria
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'

# Activar el uso de la configuración de idioma en la base de datos
USE_I18N = True

# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar las variables de entorno desde el archivo .env
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Seguridad
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'default_secret_key')
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')

# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # Django Extensions
    'crispy_forms',  # Crispy Forms
    'widget_tweaks',  # Widget Tweaks
    'debug_toolbar',  # Debug Toolbar
    'forms',  # Nuestra aplicación de formularios
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Debug Toolbar
]

# URL de la página de inicio después del login/logout
LOGIN_REDIRECT_URL = 'forms:dashboard'
LOGOUT_REDIRECT_URL = 'forms:login'

# Configurar oracledb para usar modo "thin" (sin Oracle Client)
oracledb.init_oracle_client(lib_dir=None)  # None para usar modo thin

# Configuración de la base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': os.getenv('DB_NAME', 'XE'),
        'USER': os.getenv('DB_USER', 'FORM_PIR'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'dess123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '1521'),
        'OPTIONS': {
            'threaded': True,
            'use_returning_into': False,
        },
    }
}

# Archivos estáticos y media
STATIC_URL = 'static/'
MEDIA_URL = 'media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT = BASE_DIR / "media"

# Plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# URL de la API (si es necesaria)
API_URL = os.getenv('DJANGO_API_URL', 'http://localhost:8000/api/')

# Configuración de Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Configuración de la barra lateral (sidebar) en el admin
ADMIN_SIDEBAR = True

# Configuración de Debug Toolbar
INTERNAL_IPS = [
    # ... other internal IPs ...
    "127.0.0.1",
]

# Configuración de la caché
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Configuración de la seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Configuración de internacionalización
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),




CUSTOM_SETTING = os.getenv('DJANGO_CUSTOM_SETTING', 'default_value')# Otras configuraciones personalizadas]
# Inicializar el entorno de Django
django.setup()